version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "auto-creation"
      - "github-actions"
    schedule:
      interval: daily
      time: "17:30"
      timezone: "Europe/Brussels"
    groups:
      actions-breaking:
        applies-to: version-updates
        update-types:
          - major
      actions-safe-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: "npm"
    directory: "/tools"
    labels:
      - "dependencies"
      - "auto-creation"
      - "javascript"
    schedule:
      interval: daily
      time: "17:30"
      timezone: "Europe/Brussels"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-safe-updates:
        applies-to: version-updates
        patterns:
          - "*"
