version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "auto-creation"
      - "github-actions"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/tools"
    labels:
      - "dependencies"
      - "auto-creation"
      - "javascript"
    schedule:
      interval: "weekly"
