version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "auto-creation"
      - "github-actions"
    schedule:
      interval: "weekly"
